### ISSUE TITLE
Error with Flash

### ISSUE THREAD

**Issue by murphycj** [lucapinello/CRISPResso#7]
I get the following error

```
[Command used]:
CRISPResso /Library/Frameworks/Python.framework/Versions/2.7/bin/CRISPResso -r1 43_S15_L001_R1_001.fastq.gz -r2 43_S15_L001_R2_001.fastq.gz -q 20 -a gagtgctggctctggcctggtgccacccgcctatgcccctccccctgccgtccccggccatcctgccccccagagtgctgaggtgtggggcgggccttctggggcacagcctgggcacagaggtggctgtgcgaagaggggcttgacctcggggttcagaaggggactttacgcgggaaggtactttccctccctccagctcccctcccccgcgtccttccacctctcccggtctctcccactcctcccctggccctccacagcccctcttcttcctcccctggccctctccttcctcccagtccctccccatcccctcccccctacttttcctcctccttccctcccctcctccctgtgcttcttccctgtctctctttcccgccccgctgtacctctccctctgcccctccgctccccgttcactctccctcctcccctgcccctcgacactgtccctcccc -g CGAAGAGGGGCTTGACCTCGGGG -o 43_S15_q20_out

[Execution log]:
Filtering reads with average bp quality < 20 ...
Estimating average read length...
Merging paired sequences with Flash...
[FLASH] ERROR: Maximum overlap (-49) cannot be less than the minimum overlap (4).
Please make sure you have provided the read length and fragment length
correctly.  Or, alternatively, specify the minimum and maximum overlap
manually with the --min-overlap and --max-overlap options.
[FLASH] FLASH did not complete successfully; exiting with failure status (1)
Merging error, please check your input.

ERROR: Flash failed to run, please check the log file.
```

I cannot seem to specify --max-overlap though. I' am working with 150bp PE reads from MiSeq.

**Comment by lucapinello** [comment]
Hi Charles,
It seems that in your experimental design you have a large amplicon of 464 bp but you can sequence only the ends of it since you are using 150bp PE.

Unfortunately you cannot use  CRISPResso  in this scenario since you cannot sequence the entire unmodified amplicon.

For paired end reads that means that any pair of reads should partially overlap. This is enforced since if you sequence only the ends of an amplicon you don't know what will happen inside and this will make the quantifications of indels wrong.

That is why FLASH is throwing this error since it is impossible to find any overlap for paired reads in your case.

Hope this is helpful

**Comment by murphycj** [comment]
Thanks. Yeah actually my case turned out my collaborators just gave me an amplicon sequence that was too long
